export const positionsChartModelData = {
  seriesData: [
    {
      symbol: 'EURCAD',
      basePnl: 196198.47750305105,
      baseTradedAmount: 513000000,
      currencyPair: {
        symbol: 'EURCAD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'EUR',
        terms: 'CAD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'AUDUSD',
      basePnl: 165692.85156410572,
      baseTradedAmount: 251500000,
      currencyPair: {
        symbol: 'AUDUSD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'AUD',
        terms: 'USD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'EURJPY',
      basePnl: 2011369.5979995793,
      baseTradedAmount: -1962999839,
      currencyPair: {
        symbol: 'EURJPY',
        ratePrecision: 3,
        pipsPosition: 2,
        base: 'EUR',
        terms: 'JPY',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'USDJPY',
      basePnl: 946316.672423151,
      baseTradedAmount: -170000000,
      currencyPair: {
        symbol: 'USDJPY',
        ratePrecision: 3,
        pipsPosition: 2,
        base: 'USD',
        terms: 'JPY',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'GBPUSD',
      basePnl: -1580365.920442324,
      baseTradedAmount: 842000000,
      currencyPair: {
        symbol: 'GBPUSD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'GBP',
        terms: 'USD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'EURUSD',
      basePnl: -1475313.3793809158,
      baseTradedAmount: 1271000000,
      currencyPair: {
        symbol: 'EURUSD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'EUR',
        terms: 'USD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'NZDUSD',
      basePnl: -2444298.9017461403,
      baseTradedAmount: 1199999920,
      currencyPair: {
        symbol: 'NZDUSD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'NZD',
        terms: 'USD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
    {
      symbol: 'EURAUD',
      basePnl: -27947.140182182862,
      baseTradedAmount: 361999980,
      currencyPair: {
        symbol: 'EURAUD',
        ratePrecision: 5,
        pipsPosition: 4,
        base: 'EUR',
        terms: 'AUD',
      },
      basePnlName: 'basePnl',
      baseTradedAmountName: 'baseTradedAmount',
    },
  ],
  options: {
    showYAxis: true,
    showXAxis: true,
    showLegend: false,
    useInteractiveGuideline: true,
    duration: 0,
    showValues: true,
    showControls: false,
    width: 900,
    tooltip: {
      enabled: false,
    },
    margin: {
      top: 0,
      right: 0,
      bottom: 0,
    },
  },
  yAxisValuePropertyName: 'baseTradedAmount',
}
