export { OpenFin, openDesktopWindow } from './adapter'
export { isParentAppOpenfinLauncher } from './adapter/launcherUtils'
export { OpenFinLimitChecker } from './limitChecker/openFin'
export { OpenFinHeader } from './components'
export * from './excel'
