apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bot
  template:
    metadata:
      labels:
        component: bot
    spec:
      containers:
        - name: bot
          image: reactivetradercloud/bot:4765
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            - name: BOT_NAME
              valueFrom:
                configMapKeyRef:
                  name: bot-config
                  key: bot-name
            - name: BOT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: bot-config
                  key: bot-address
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: syphony-secrets
                  key: rsa-privatekey
