#! /bin/bash

echo "Pricing"

startCommand=`cat "../../../../../src/server/PricingInstance.bat"`
waitCommand="while true; do echo ping; sleep 60; done"

docker rm pricing 2&> garbage

docker run -d --net=host                     \
     --name pricing                          \
     weareadaptive/reactive-trader-server    \
     bash -c "$startCommand && $waitCommand" \
     > container_id 

rm garbage

echo "  started"
echo " "
