#! /bin/bash

build=""
if [[ $1 != "" ]];then
  build=".$1"
fi

echo "ReferenceDataRead"

. ../../../config

startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run ref"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm reference 2&> garbage

docker run -d --net=host                      \
     --name reference                         \
     $serversContainer$build                  \
     bash -c "$startCommand && $waitCommand"  \
     > container_id 

rm garbage

echo " "
