apiVersion: v1
kind: Service
metadata:
    name: "__SERVICE__"
    namespace: "__NAMESPACE__"
    labels:
        name: "__SERVICE____MAJOR__"
spec:
    selector:
        name: "__SERVICE____MAJOR__"
    ports:
    -   port: 80
        targetPort: 80
        name: "http"
    -   port: 443
        targetPort: 443
        name: "https"
    -   port: 8000
        targetPort: 8000
        name: "broker"
    -   port: 1113
        targetPort: 1113
        name: "eventstore-tcp"
    -   port: 2113
        targetPort: 2113
        name: "eventstore"
    type: "LoadBalancer"
    __LOAD_BALANCER_IP__
