export { default as OpenFin } from './openFin'
export { openDesktopWindow, isCurrentWindowDocked } from './window'
export { isParentAppOpenfinLauncher } from './launcherUtils'
export { createExcelApp } from '../../excelApp'
export { platformEpics } from './epics'
