#!/bin/bash

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

for directory in broker crossbar dotnet eventstore gcloud nginx node nsgate populatedEventstore servers testtools web/nginx web/npminstall minikubegate;
do
    build_directory=${root_directory}/deploy/docker/build/$directory/build
    if [[ -e ${build_directory} ]]
    then rm -r ${build_directory}
    fi
done
