#! /bin/bash

if [[ $# != 1 ]];then
  echo " "
  echo " usage:"
  echo " "
  echo "   testAll BUILD_NUMBER"
  echo " "
  echo "   ie: ./testAll 294"
  echo " "
  exit 1
fi
build=$1

# fail fast
set euo -pipefail

# get and control config
. ../config

echo " "
echo "Starting ReactiveTrader ..."
./killAll > garbage
./runAll $build > garbage
docker ps


echo " "
echo "Starting local tests ..."
docker run -a STDOUT \
  --net=host $serversContainer:$vMajor.$vMinor.$build \
  bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.IntegrationTests test -parallel none"

echo " "
./killAll > garbage
rm garbage
