apiVersion: v1
kind: Service
metadata:
  name: "broker"
  labels:
    name: "broker"
    major: "<% reactivetrader.servers.major %>"
spec:
  selector:
    name: "broker"
    major: "<% reactivetrader.servers.major %>"
  ports:
  - port: 8080
    targetPort: 8080
    name: "ws"
