#! /bin/bash

echo "ReferenceDataRead"

. ../../../../config

startCommand="dnx -p Adaptive.ReactiveTrader.Server.ReferenceDataRead run"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm reference 2&> garbage

docker run -d --net=host                       \
     --name reference                          \
     $serversContainer:$vMajor.$vMinor.$vBuild \
     bash -c "$startCommand && $waitCommand"   \
     > container_id 

rm garbage

echo "  started"
echo " "
