apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  type: ClusterIP
  selector:
    component: broker
  ports:
    - port: 5672
      name: tcp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
    - port: 15674
      name: ws
      targetPort: 15674
