#! /bin/bash

echo "Loading containers"

for container in "ubuntu mono crossbar eventstore nginx"
do
  if [[ -e ~/docker/$container.tar ]]; then 
    docker load -i ~/docker/$container.tar && echo "$container loaded" 
  fi
done
