#! /bin/bash

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# create cluster
gcloud="${root_directory}/deploy/clis/gcloud"
${gcloud} container clusters \
    create $kube_cluster \
        --zone $kube_zone \
        --machine-type $kube_machinetype \
        --num-nodes $kube_num_nodes
