#! /bin/bash

if [[ ! -f ../config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config"
    exit 1
fi

# load config
. ../config

# create cluster
./gcloud container clusters create $kube_cluster             \
                            --zone $kube_zone                \
                            --machine-type $kube_machinetype \
                            --num-nodes $kube_num_nodes
