#! /bin/bash

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# delete cluster
gcloud="${root_directory}/deploy/clis/gcloud"
${gcloud} container clusters delete $kube_cluster
