#! /bin/bash

cluster=$1
if [[ $cluster == "" ]];then
    echo "Usage:"
    echo "$0 <cluster_name>"
    echo " "
    echo "This commamd let you delete the cluster with name defined as parameter"
    exit 1
fi

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# delete cluster
gcloud="${root_directory}/deploy/clis/gcloud"
${gcloud} container clusters delete $cluster
