#! /bin/bash

set -euo pipefail

cacheFolder=$(pwd)/../cache

if [[ ! -f ../config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config and fill informations"
    echo " "
    exit 1
fi
. ../config

docker run --rm -ti                       \
  -v /$cacheFolder/.config://root/.config \
  -v /$cacheFolder/.kube://root/.kube     \
  $gcloudContainer:$vGcloud gcloud $@
