#! /bin/bash

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

cluster=$1
if [[ $cluster == "" ]];then
    echo "Usage:"
    echo "  $0 <cluster_name>"
    echo " "
    echo "This commamd let you get credentials from the cluster with name defined as parameter"
    echo "existing cluster names:"
    . ${root_directory}/deploy/googleCloudEngine/showClusters.sh
    showClusters
    echo " "
    exit 1
fi

# load configuration
. ${root_directory}/deploy/config

# get cluster credentials
gcloud="${root_directory}/deploy/clis/gcloud"
${gcloud} container clusters get-credentials $cluster
