#! /bin/bash

if [[ ! -f ../config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config and fill informations"
    exit 1
fi

. ../config

./gcloud container clusters get-credentials $kube_cluster
