#! /bin/bash

if [[ ! -f ./config/config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config"
    exit 1
fi

. ./config/config

./gcloud config set project $kube_project
./gcloud config set compute/zone $kube_zone
./gcloud config set container/cluster $kube_cluster
