#! /bin/bash

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# define project
gcloud="${root_directory}/deploy/clis/gcloud"
${gcloud} config set project $kube_project
${gcloud} config set compute/zone $kube_zone
${gcloud} config set container/cluster $kube_cluster
