export const LINE_CHART_WIDTH = 280
export const LINE_CHART_HEIGHT = 170
export const Y_LEGENDS_WIDTH = 40
export const X_LEGENDS_HEIGHT = 30

export const TOTAL_WIDTH = LINE_CHART_WIDTH + Y_LEGENDS_WIDTH
export const TOTAL_HEIGHT = LINE_CHART_HEIGHT + X_LEGENDS_HEIGHT
