#! /bin/bash

scream() {
    echo "error on $1"
    exit 1
}

for server in "web" "eventstore" "broker" "referencedataread" "pricing" "tradeexecution" "blotter"
do
    cd $server
    ./run  || scream $server
    ./test || scream $server
    cd ..
done
