#! /bin/bash

echo "Reference"

startCommand=`cat "../../../../../src/server/ReferenceInstance.bat"`
waitCommand="while true; do echo ping; sleep 60; done"

docker rm reference 2&> garbage

docker run -d --net=host                     \
     --name reference                        \
     weareadaptive/at-servers                \
     bash -c "$startCommand && $waitCommand" \
     > container_id 

rm garbage

echo "  started"
echo " "
