#! /bin/bash
# Here are the list of version for every part of the deployment

# SSL Domain
# ==========
domainName="adaptivecluster.com"

# VERSIONING
# ==========
vMajor="0"
vMinor="0"

brokerContainer_major="0"
brokerContainer_minor="0"
brokerContainer="reactivetrader/broker:$brokerContainer_major.$brokerContainer_minor"

serversContainer="reactivetrader/servers"
webContainer="reactivetrader/web"
populatedEventstoreContainer="reactivetrader/eventstore"

# OS
ubuntuContainer="ubuntu:14.04.2"
vDebian="8.2"

# crossbar
vCrossbar="0.11.1"
crossbarContainer_major="0"
crossbarContainer_minor="0"
crossbarContainer="weareadaptive/crossbar:$crossbarContainer_major.$crossbarContainer_minor"

# eventstore
vEventstore="3.3.0"
eventstoreContainer="weareadaptive/eventstore"

# node
vNode="5.3.0"
nodeContainer="weareadaptive/node"

# nginx
vNginx="1.9.7"
nginxContainer="weareadaptive/nginx"

# kubernetes
vKubernetes="1.1.3"
kubernetesContainer="weareadaptive/kubernetes"

# mono
vDnx="1.0.0-rc1-final"
monoContainer="weareadaptive/mono"

# TestTool
testtools_major="1"
testtools_minor="0"
testtoolsContainer="weareadaptive/testtools"

# gcloud
gcloud_major="1"
gcloud_minor="0"
gcloudContainer="weareadaptive/gcloud"

# fluentd
fluentd_major="0"
fluentd_minor="0"
fluentdContainer="weareadaptive/fluentd"

# nsgate
nsGate_major="0"
nsGate_minor="1"
nsGateContainer="weareadaptive/nsgate"

# jq
vJq="1.5"


# GCLOUD
# ======
# You need to change this ones
kube_cluster="cluster"

# other default parameters
kube_project="adaptive-trader"
kube_num_nodes=1

# kube_machinetype="f1-micro"       #   0.6 Go
# kube_machinetype="g1-small"       #   1.7 Go
kube_machinetype="n1-standard-1"  #   3.7 Go
# kube_machinetype="n1-standard-2"  #   7.5 Go
# kube_machinetype="n1-standard-4"  #  15   Go
# kube_machinetype="n1-standard-8"  #  30   Go
# kube_machinetype="n1-standard-16" #  60   Go
# kube_machinetype="n1-highcpu-2"   #   1.8 Go
# kube_machinetype="n1-highcpu-4"   #   3.6 Go
# kube_machinetype="n1-highcpu-8"   #   7.2 Go
# kube_machinetype="n1-highcpu-16"  #  14.4 Go
# kube_machinetype="n1-highmem-2"   #  13   Go
# kube_machinetype="n1-highmem-4"   #  26   Go
# kube_machinetype="n1-highmem-8"   #  52   Go
# kube_machinetype="n1-highmem-16"  # 104   Go

# kube_zone="asia-east1-a"
# kube_zone="asia-east1-b"
# kube_zone="asia-east1-c"
# kube_zone="europe-west1-b"
kube_zone="europe-west1-c"
# kube_zone="europe-west1-d"
# kube_zone="us-central1-a"
# kube_zone="us-central1-b"
# kube_zone="us-central1-c"
# kube_zone="us-central1-f"
