#! /bin/bash
# Here are the list of version for every part of the deployment

# VERSIONING
# ==========
vMajor="0"
vMinor="0"

# Reactive Trader
brokerContainer_major="0"
brokerContainer_minor="0"
brokerContainer="reactivetrader/broker:$brokerContainer_major.$brokerContainer_minor"

populatedEventstoreContainer_major="0"
populatedEventstoreContainer_minor="0"
populatedEventstoreContainer="reactivetrader/eventstore:$populatedEventstoreContainer_major.$populatedEventstoreContainer_minor"

serversContainer_major="0"
serversContainer_minor="1"
serversContainer="reactivetrader/servers:$serversContainer_major.$serversContainer_minor"

webContainer_major="0"
webContainer_minor="0"
webContainer="reactivetrader/web:$webContainer_major.$webContainer_minor"

# Other containers
# OS
ubuntuContainer="ubuntu:14.04.2"
debianContainer="debian:8.2"

# crossbar
vCrossbar="17.5.1"
crossbarContainer_major="17"
crossbarContainer_minor="5"
crossbarContainer="weareadaptive/crossbar:$crossbarContainer_major.$crossbarContainer_minor"

# eventstore
vEventstore="3.3.0"
eventstoreContainer_major="0"
eventstoreContainer_minor="0"
eventstoreContainer="weareadaptive/eventstore:$eventstoreContainer_major.$eventstoreContainer_minor"

# node
vNode="6.2.1"
nodeContainer_major="6"
nodeContainer_minor="2"
nodeContainer="weareadaptive/node:$nodeContainer_major.$nodeContainer_minor"

# nginx
vNginx="1.12.0"
officialNginxContainer="nginx:$vNginx"
nginxContainer_major="1"
nginxContainer_minor="12"
nginxContainer="weareadaptive/nginx:$nginxContainer_major.$nginxContainer_minor"

# dotnet
dotnetversion="dotnet-dev-1.0.0-preview2.1-003177"
dotnetContainer_major="1"
dotnetContainer_minor="1"
dotnetContainer="weareadaptive/dotnet:$dotnetContainer_major.$dotnetContainer_minor"

# TestTool
vJq="1.5"
testtools_major="1"
testtools_minor="1"
testtoolsContainer_base="weareadaptive/testtools"
testtoolsContainer="$testtoolsContainer_base:$testtools_major.$testtools_minor"
testtoolsContainer_latest="$testtoolsContainer_base:latest"

# gcloud
gcloudContainer_major="1"
gcloudContainer_minor="2"
gcloudContainer="weareadaptive/gcloud:$gcloudContainer_major.$gcloudContainer_minor"

# Clusters Access
# nsgate
nsGateContainer_major="0"
nsGateContainer_minor="2"
nsGateContainer="weareadaptive/nsgate:$nsGateContainer_major.$nsGateContainer_minor"

minikubegate_major="0"
minikubegate_minor="0"
minikubegate_image="weareadaptive/minikubegate:$minikubegate_major.$minikubegate_minor"

# GCLOUD
# ======
# other default parameters
kube_project="adaptive-trader"
kube_num_nodes=1

kube_machinetype="n1-standard-1"  #   3.7 Go
# kube_machinetype="n1-highmem-2"   #  13   Go
kube_zone="europe-west1-c"

config_gcloud_externalip_dev="35.195.122.136"
config_gcloud_externalip_cluster="104.155.13.196"

# DOCKER-COMPOSE
# ==============
docker_compose_file="docker-compose.yml"

# LOCAL DOCKER
# ============
docker_network="bridge"
