#! /bin/bash
# Here are the list of version for every part of the deployment

vMajor="0"
vMinor="0"
vBuild="spike"

# crossbar/broker container
vUbuntu="14.04.2"
vCrossbar="0.11.1"

# eventStore container
vEventstore="3.3.0"

# mono/servers container
vDnx="1.0.0-rc1-final"

# node/web container
vNode="5.1.0"

# gcloud container
vDebian="8.2"

# TestTools container
vTesttools="1.0"
