apiVersion: v1
kind: Service
metadata:
  name: "__SERVICE__"
  namespace: "__NAMESPACE__"
  labels:
    name: "__SERVICE____MAJOR__"
spec:
  selector:
    name: "eventstore"
  ports:
  - port: 1113
    targetPort: 1113
    name: "stream"
  - port: 2113
    targetPort: 2113
    name: "http"
  type: "LoadBalancer"
