export const theme = {
  color: {
    "Colors/Text/text-primary (900)": "#f7f7f7",
    "Colors/Text/text-tertiary (600)": "#a3a3a3",
    "Colors/Text/text-error-primary (600)": "#c34646",
    "Colors/Text/text-warning-primary (600)": "#fdb022",
    "Colors/Text/text-success-primary (600)": "#47cd89",
    "Colors/Text/text-white": "#ffffff",
    "Colors/Text/text-secondary (700)": "#d6d6d6",
    "Colors/Text/text-disabled": "#737373",
    "Colors/Text/text-secondary_hover": "#e5e5e5",
    "Colors/Text/text-tertiary_hover": "#d6d6d6",
    "Colors/Text/text-brand-secondary (700)": "#d6d6d6",
    "Colors/Text/text-placeholder": "#737373",
    "Colors/Text/text-placeholder_subtle": "#424242",
    "Colors/Text/text-brand-tertiary (600)": "#a3a3a3",
    "Colors/Text/text-quaternary (500)": "#737373",
    "Colors/Text/text-brand-primary (900)": "#8e90f9",
    "Colors/Text/text-primary_on-brand": "#ffffff",
    "Colors/Text/text-secondary_on-brand": "#d9dafd",
    "Colors/Text/text-tertiary_on-brand": "#c0c2fc",
    "Colors/Text/text-quaternary_on-brand": "#a7a9fa",
    "Colors/Text/text-brand-tertiary_alt": "#f7f7f7",
    "Colors/Border/border-secondary": "#292929",
    "Colors/Border/border-error_subtle": "#890c21",
    "Colors/Border/border-primary": "#424242",
    "Colors/Border/border-brand": "#8184f8",
    "Colors/Border/border-disabled": "#424242",
    "Colors/Border/border-error": "#c41230",
    "Colors/Border/border-disabled_subtle": "#292929",
    "Colors/Border/border-tertiary": "#292929",
    "Colors/Border/border-brand_alt": "#424242",
    "Colors/Background/bg-primary": "#0f0f0f",
    "Colors/Background/bg-tertiary": "#292929",
    "Colors/Background/bg-brand-primary": "#8184f8",
    "Colors/Background/bg-error-secondary": "#890c21",
    "Colors/Background/bg-warning-primary": "#f79009",
    "Colors/Background/bg-warning-secondary": "#dc6803",
    "Colors/Background/bg-success-primary": "#17b26a",
    "Colors/Background/bg-success-secondary": "#079455",
    "Colors/Background/bg-brand-solid": "#676ac6",
    "Colors/Background/bg-secondary-solid": "#525252",
    "Colors/Background/bg-error-solid": "#890c21",
    "Colors/Background/bg-warning-solid": "#dc6803",
    "Colors/Background/bg-success-solid": "#079455",
    "Colors/Background/bg-secondary_hover": "#424242",
    "Colors/Background/bg-primary_hover": "#292929",
    "Colors/Background/bg-disabled": "#292929",
    "Colors/Background/bg-active": "#292929",
    "Colors/Background/bg-brand-solid_hover": "#8184f8",
    "Colors/Background/bg-error-primary": "#a50e28",
    "Colors/Background/bg-brand-secondary": "#676ac6",
    "Colors/Background/bg-secondary": "#1f1f1f",
    "Colors/Background/bg-disabled_subtle": "#292929",
    "Colors/Background/bg-quaternary": "#424242",
    "Colors/Background/bg-primary_alt": "#141414",
    "Colors/Background/bg-brand-primary_alt": "#1f1f1f",
    "Colors/Background/bg-secondary_alt": "#0f0f0f",
    "Colors/Background/bg-overlay": "#292929",
    "Colors/Background/bg-secondary_subtle": "#141414",
    "Colors/Background/bg-brand-section": "#1f1f1f",
    "Colors/Background/bg-brand-section_subtle": "#0f0f0f",
    "Colors/Background/bg-primary-solid": "#f5f5f5",
    "Colors/Foreground/fg-secondary (700)": "#d6d6d6",
    "Colors/Foreground/fg-warning-primary": "#f79009",
    "Colors/Foreground/fg-success-primary": "#17b26a",
    "Colors/Foreground/fg-white": "#ffffff",
    "Colors/Foreground/fg-success-secondary": "#47cd89",
    "Colors/Foreground/fg-secondary_hover": "#e5e5e5",
    "Colors/Foreground/fg-primary (900)": "#ffffff",
    "Colors/Foreground/fg-disabled": "#737373",
    "Colors/Foreground/fg-quaternary (500)": "#a3a3a3",
    "Colors/Foreground/fg-quaternary_hover": "#d6d6d6",
    "Colors/Foreground/fg-brand-secondary (500)": "#8184f8",
    "Colors/Foreground/fg-brand-primary (600)": "#8184f8",
    "Colors/Foreground/fg-quinary (400)": "#737373",
    "Colors/Foreground/fg-quinary_hover": "#a3a3a3",
    "Colors/Foreground/fg-error-primary": "#a50e28",
    "Colors/Foreground/fg-disabled_subtle": "#525252",
    "Colors/Foreground/fg-warning-secondary": "#fdb022",
    "Colors/Foreground/fg-error-secondary": "#c41230",
    "Colors/Foreground/fg-senary (300)": "#525252",
    "Colors/Foreground/fg-tertiary (600)": "#a3a3a3",
    "Colors/Foreground/fg-tertiary_hover": "#d6d6d6",
    "Colors/Foreground/fg-brand-primary_alt": "#d6d6d6",
    "Colors/Effects/Shadows/shadow-xs": "#1313160d",
    "Colors/Effects/Shadows/shadow-sm_02": "#1313160f",
    "Colors/Effects/Shadows/shadow-lg_01": "#131316",
    "Colors/Effects/Shadows/shadow-lg_02": "#131316cc",
    "Colors/Effects/Shadows/shadow-sm_01": "#1313161a",
    "Colors/Effects/Shadows/shadow-3xl": "#13131624",
    "Colors/Effects/Shadows/shadow-2xl": "#1313162e",
    "Colors/Effects/Shadows/shadow-md_01": "#1313161a",
    "Colors/Effects/Shadows/shadow-md_02": "#1313160f",
    "Colors/Effects/Shadows/shadow-xl_01": "#13131614",
    "Colors/Effects/Shadows/shadow-xl_02": "#13131608",
    "Colors/Effects/Shadows/shadow-skeumorphic-inner": "#1313160d",
    "Colors/Effects/Shadows/shadow-skeumorphic-inner-border": "#13131640",
    "Colors/Effects/Focus rings/focus-ring": "#2e90fa",
    "Colors/Effects/Focus rings/focus-ring-error": "#a50e28",
    "Component colors/Utility/Blue/utility-blue-600": "#53b1fd",
    "Component colors/Utility/Blue/utility-blue-700": "#84caff",
    "Component colors/Utility/Blue/utility-blue-500": "#2e90fa",
    "Component colors/Utility/Blue/utility-blue-200": "#1849a9",
    "Component colors/Utility/Blue/utility-blue-50": "#102a56",
    "Component colors/Utility/Blue/utility-blue-100": "#194185",
    "Component colors/Utility/Blue/utility-blue-400": "#1570ef",
    "Component colors/Utility/Blue/utility-blue-300": "#175cd3",
    "Component colors/Utility/Brand/utility-brand-600": "#8e90f9",
    "Component colors/Utility/Brand/utility-brand-700": "#a7a9fa",
    "Component colors/Utility/Brand/utility-brand-500": "#8184f8",
    "Component colors/Utility/Brand/utility-brand-200": "#41427c",
    "Component colors/Utility/Brand/utility-brand-50": "#0d0d19",
    "Component colors/Utility/Brand/utility-brand-100": "#27284a",
    "Component colors/Utility/Brand/utility-brand-400": "#676ac6",
    "Component colors/Utility/Brand/utility-brand-50_alt": "#141414",
    "Component colors/Utility/Brand/utility-brand-100_alt": "#292929",
    "Component colors/Utility/Brand/utility-brand-200_alt": "#424242",
    "Component colors/Utility/Brand/utility-brand-400_alt": "#525252",
    "Component colors/Utility/Brand/utility-brand-500_alt": "#737373",
    "Component colors/Utility/Brand/utility-brand-600_alt": "#a3a3a3",
    "Component colors/Utility/Brand/utility-brand-700_alt": "#d6d6d6",
    "Component colors/Utility/Brand/utility-brand-300": "#4d4f95",
    "Component colors/Utility/Brand/utility-brand-900": "#d9dafd",
    "Component colors/Utility/Brand/utility-brand-800": "#c0c2fc",
    "Component colors/Utility/Brand/utility-brand-300_alt": "#424242",
    "Component colors/Utility/Brand/utility-brand-800_alt": "#e5e5e5",
    "Component colors/Utility/Brand/utility-brand-900_alt": "#f5f5f5",
    "Component colors/Utility/Gray/utility-gray-700": "#d6d6d6",
    "Component colors/Utility/Gray/utility-gray-600": "#a3a3a3",
    "Component colors/Utility/Gray/utility-gray-500": "#737373",
    "Component colors/Utility/Gray/utility-gray-200": "#424242",
    "Component colors/Utility/Gray/utility-gray-50": "#141414",
    "Component colors/Utility/Gray/utility-gray-100": "#292929",
    "Component colors/Utility/Gray/utility-gray-400": "#525252",
    "Component colors/Utility/Gray/utility-gray-300": "#424242",
    "Component colors/Utility/Gray/utility-gray-900": "#f5f5f5",
    "Component colors/Utility/Gray/utility-gray-800": "#e5e5e5",
    "Component colors/Utility/Error/utility-error-600": "#c41230",
    "Component colors/Utility/Error/utility-error-700": "#d14159",
    "Component colors/Utility/Error/utility-error-500": "#a50e28",
    "Component colors/Utility/Error/utility-error-200": "#500713",
    "Component colors/Utility/Error/utility-error-50": "#34040d",
    "Component colors/Utility/Error/utility-error-100": "#34040d",
    "Component colors/Utility/Error/utility-error-400": "#890c21",
    "Component colors/Utility/Error/utility-error-300": "#6d091a",
    "Component colors/Utility/Warning/utility-warning-600": "#fdb022",
    "Component colors/Utility/Warning/utility-warning-700": "#fec84b",
    "Component colors/Utility/Warning/utility-warning-500": "#f79009",
    "Component colors/Utility/Warning/utility-warning-200": "#93370d",
    "Component colors/Utility/Warning/utility-warning-50": "#4e1d09",
    "Component colors/Utility/Warning/utility-warning-100": "#7a2e0e",
    "Component colors/Utility/Warning/utility-warning-400": "#dc6803",
    "Component colors/Utility/Warning/utility-warning-300": "#b54708",
    "Component colors/Utility/Success/utility-success-600": "#47cd89",
    "Component colors/Utility/Success/utility-success-700": "#75e0a7",
    "Component colors/Utility/Success/utility-success-500": "#17b26a",
    "Component colors/Utility/Success/utility-success-200": "#085d3a",
    "Component colors/Utility/Success/utility-success-50": "#053321",
    "Component colors/Utility/Success/utility-success-100": "#074d31",
    "Component colors/Utility/Success/utility-success-400": "#079455",
    "Component colors/Utility/Success/utility-success-300": "#067647",
    "Component colors/Utility/Orange/utility-orange-600": "#f38744",
    "Component colors/Utility/Orange/utility-orange-700": "#f7b27a",
    "Component colors/Utility/Orange/utility-orange-500": "#ef6820",
    "Component colors/Utility/Orange/utility-orange-200": "#932f19",
    "Component colors/Utility/Orange/utility-orange-50": "#511c10",
    "Component colors/Utility/Orange/utility-orange-100": "#772917",
    "Component colors/Utility/Orange/utility-orange-400": "#e04f16",
    "Component colors/Utility/Orange/utility-orange-300": "#b93815",
    "Component colors/Utility/Blue dark/utility-blue-dark-600": "#528bff",
    "Component colors/Utility/Blue dark/utility-blue-dark-700": "#84adff",
    "Component colors/Utility/Blue dark/utility-blue-dark-500": "#2970ff",
    "Component colors/Utility/Blue dark/utility-blue-dark-200": "#0040c1",
    "Component colors/Utility/Blue dark/utility-blue-dark-50": "#002266",
    "Component colors/Utility/Blue dark/utility-blue-dark-100": "#00359e",
    "Component colors/Utility/Blue dark/utility-blue-dark-400": "#155eef",
    "Component colors/Utility/Blue dark/utility-blue-dark-300": "#004eeb",
    "Component colors/Utility/Indigo/utility-indigo-600": "#8098f9",
    "Component colors/Utility/Indigo/utility-indigo-700": "#a4bcfd",
    "Component colors/Utility/Indigo/utility-indigo-500": "#6172f3",
    "Component colors/Utility/Indigo/utility-indigo-200": "#2d31a6",
    "Component colors/Utility/Indigo/utility-indigo-50": "#1f235b",
    "Component colors/Utility/Indigo/utility-indigo-100": "#2d3282",
    "Component colors/Utility/Indigo/utility-indigo-400": "#444ce7",
    "Component colors/Utility/Indigo/utility-indigo-300": "#3538cd",
    "Component colors/Utility/Fuchsia/utility-fuchsia-600": "#e478fa",
    "Component colors/Utility/Fuchsia/utility-fuchsia-700": "#eeaafd",
    "Component colors/Utility/Fuchsia/utility-fuchsia-500": "#d444f1",
    "Component colors/Utility/Fuchsia/utility-fuchsia-200": "#821890",
    "Component colors/Utility/Fuchsia/utility-fuchsia-50": "#47104c",
    "Component colors/Utility/Fuchsia/utility-fuchsia-100": "#6f1877",
    "Component colors/Utility/Fuchsia/utility-fuchsia-400": "#ba24d5",
    "Component colors/Utility/Fuchsia/utility-fuchsia-300": "#9f1ab1",
    "Component colors/Utility/Pink/utility-pink-600": "#f670c7",
    "Component colors/Utility/Pink/utility-pink-700": "#faa7e0",
    "Component colors/Utility/Pink/utility-pink-500": "#ee46bc",
    "Component colors/Utility/Pink/utility-pink-200": "#9e165f",
    "Component colors/Utility/Pink/utility-pink-50": "#4e0d30",
    "Component colors/Utility/Pink/utility-pink-100": "#851651",
    "Component colors/Utility/Pink/utility-pink-400": "#dd2590",
    "Component colors/Utility/Pink/utility-pink-300": "#c11574",
    "Component colors/Utility/Purple/utility-purple-600": "#9b8afb",
    "Component colors/Utility/Purple/utility-purple-700": "#bdb4fe",
    "Component colors/Utility/Purple/utility-purple-500": "#7a5af8",
    "Component colors/Utility/Purple/utility-purple-200": "#4a1fb8",
    "Component colors/Utility/Purple/utility-purple-50": "#27115f",
    "Component colors/Utility/Purple/utility-purple-100": "#3e1c96",
    "Component colors/Utility/Purple/utility-purple-400": "#6938ef",
    "Component colors/Utility/Purple/utility-purple-300": "#5925dc",
    "Component colors/Utility/Orange dark/utility-orange-dark-600": "#ff692e",
    "Component colors/Utility/Orange dark/utility-orange-dark-700": "#ff9c66",
    "Component colors/Utility/Orange dark/utility-orange-dark-500": "#ff4405",
    "Component colors/Utility/Orange dark/utility-orange-dark-200": "#97180c",
    "Component colors/Utility/Orange dark/utility-orange-dark-50": "#57130a",
    "Component colors/Utility/Orange dark/utility-orange-dark-100": "#771a0d",
    "Component colors/Utility/Orange dark/utility-orange-dark-400": "#e62e05",
    "Component colors/Utility/Orange dark/utility-orange-dark-300": "#bc1b06",
    "Component colors/Utility/Blue light/utility-blue-light-600": "#36bffa",
    "Component colors/Utility/Blue light/utility-blue-light-700": "#7cd4fd",
    "Component colors/Utility/Blue light/utility-blue-light-500": "#0ba5ec",
    "Component colors/Utility/Blue light/utility-blue-light-200": "#065986",
    "Component colors/Utility/Blue light/utility-blue-light-50": "#062c41",
    "Component colors/Utility/Blue light/utility-blue-light-100": "#0b4a6f",
    "Component colors/Utility/Blue light/utility-blue-light-400": "#0086c9",
    "Component colors/Utility/Blue light/utility-blue-light-300": "#026aa2",
    "Component colors/Utility/Gray blue/utility-gray-blue-600": "#717bbc",
    "Component colors/Utility/Gray blue/utility-gray-blue-700": "#b3b8db",
    "Component colors/Utility/Gray blue/utility-gray-blue-500": "#4e5ba6",
    "Component colors/Utility/Gray blue/utility-gray-blue-200": "#293056",
    "Component colors/Utility/Gray blue/utility-gray-blue-50": "#101323",
    "Component colors/Utility/Gray blue/utility-gray-blue-100": "#101323",
    "Component colors/Utility/Gray blue/utility-gray-blue-400": "#3e4784",
    "Component colors/Utility/Gray blue/utility-gray-blue-300": "#363f72",
    "Component colors/Components/Tooltips/tooltip-supporting-text": "#d6d6d6",
    "Component colors/Components/Buttons/Brand/button-brand-bg": "#8184f8",
    "Component colors/Components/Buttons/Brand/button-brand-bg_hover":
      "#4d4f95",
    "Component colors/Components/Buttons/Brand/button-brand-fg": "#000000",
    "Component colors/Components/Buttons/Brand/button-brand-fg_hover":
      "#ffffff",
    "Component colors/Components/Buttons/Secondary/button-secondary-bg":
      "#141414",
    "Component colors/Components/Buttons/Secondary/button-secondary-bg_hover":
      "#292929",
    "Component colors/Components/Buttons/Secondary/button-secondary-fg":
      "#d6d6d6",
    "Component colors/Components/Buttons/Secondary/button-secondary-fg_hover":
      "#f5f5f5",
    "Component colors/Components/Buttons/Secondary/button-secondary-border":
      "#424242",
    "Component colors/Components/Buttons/Secondary/button-secondary-border_hover":
      "#424242",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-bg":
      "#141414",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-bg_hover":
      "#292929",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-border_hover":
      "#424242",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-border":
      "#424242",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-fg":
      "#d6d6d6",
    "Component colors/Components/Buttons/Secondary color/button-secondary-color-fg_hover":
      "#f5f5f5",
    "Component colors/Components/Buttons/Primary error/button-primary-error-fg":
      "#ffffff",
    "Component colors/Components/Buttons/Primary error/button-primary-error-fg_hover":
      "#ffffff",
    "Component colors/Components/Buttons/Primary error/button-primary-error-bg":
      "#890c21",
    "Component colors/Components/Buttons/Primary error/button-primary-error-bg_hover":
      "#6d091a",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-fg":
      "#e28897",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-fg_hover":
      "#f3d0d6",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-bg":
      "#34040d",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-bg_hover":
      "#34040d",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-border":
      "#500713",
    "Component colors/Components/Buttons/Secondary error/button-secondary-error-border_hover":
      "#6d091a",
    "Component colors/Components/Buttons/Tertiary/button-tertiary-fg":
      "#a3a3a3",
    "Component colors/Components/Buttons/Tertiary/button-tertiary-fg_hover":
      "#e5e5e5",
    "Component colors/Components/Buttons/Tertiary/button-tertiary-bg_hover":
      "#292929",
    "Component colors/Components/Buttons/Tertiary color/button-tertiary-color-fg":
      "#d6d6d6",
    "Component colors/Components/Buttons/Tertiary color/button-tertiary-color-fg_hover":
      "#f5f5f5",
    "Component colors/Components/Buttons/Tertiary color/button-tertiary-color-bg_hover":
      "#292929",
    "Component colors/Components/Buttons/Tertiary error/button-tertiary-error-fg":
      "#d14159",
    "Component colors/Components/Buttons/Tertiary error/button-tertiary-error-fg_hover":
      "#e28897",
    "Component colors/Components/Buttons/Tertiary error/button-tertiary-error-bg_hover":
      "#34040d",
    "Component colors/Components/Toggles/toggle-button-fg_disabled": "#525252",
    "Colors/Border/border-warning": "#f79009",
    "Colors/Border/border-warning_subtle": "#a15c07",
    "Colors/Text/text-buy-primary": "#8184f8",
    "Colors/Text/text-sell-primary": "#f63d68",
    "Colors/Background/bg-sell-primary": "#c01048",
    "Colors/Background/bg-sell-primary_hover": "#e31b54",
    "Colors/Background/bg-buy-primary": "#8e90f9",
    "Colors/Background/bg-buy-primary_hover": "#676ac6",
    "Colors/Border/border-success": "#079455",
    "Component colors/Utility/Data/utility-data-positive-50": "#cce4cc",
    "Component colors/Utility/Data/utility-data-positive-100": "#7fbb7f",
    "Component colors/Utility/Data/utility-data-positive-200": "#339233",
    "Component colors/Utility/Data/utility-data-positive-300": "#007700",
    "Component colors/Utility/Data/utility-data-positive-400": "#005a00",
    "Component colors/Utility/Data/utility-data-positive-500": "#004b00",
    "Component colors/Utility/Data/utility-data-positive-600": "#003b00",
    "Component colors/Utility/Data/utility-data-positive-700": "#002c00",
    "Component colors/Utility/Red/utility-red-700": "#e28897",
    "Component colors/Utility/Red/utility-red-600": "#d14159",
    "Component colors/Utility/Red/utility-red-500": "#c41230",
    "Component colors/Utility/Red/utility-red-400": "#a50e28",
    "Component colors/Utility/Red/utility-red-300": "#890c21",
    "Component colors/Utility/Red/utility-red-200": "#6d091a",
    "Component colors/Utility/Red/utility-red-100": "#500713",
    "Component colors/Utility/Red/utility-red-50": "#34040d",
    "Component colors/Components/Buttons/Primary/button-primary-bg": "#292929",
    "Component colors/Components/Buttons/Primary/button-primary-bg_hover":
      "#424242",
    "Component colors/Components/Buttons/Primary/button-primary-fg": "#d6d6d6",
    "Component colors/Components/Buttons/Primary/button-primary-fg_hover":
      "#fcfcfc",
    "Component colors/Components/Buttons/Primary/button-primary-border":
      "#424242",
    "Component colors/Components/Buttons/Primary/button-primary-border_hover":
      "#424242",
    "Component colors/Components/Buttons/Primary/button-primary-fg_subtle":
      "#a3a3a3",
    "Colors/Border/border-sell": "#f63d68",
    "Colors/Border/border-buy": "#8184f8",
    "Colors/Text/text-black": "#000000",
    "Colors/Text/text-primary_alt": "#0f0f0f",
    "Colors/Border/border-hover": "#737373",
  },
  radius: {
    none: "0px",
    xxs: "2px",
    xs: "4px",
    sm: "6px",
    md: "8px",
    xl: "12px",
    "2xl": "16px",
    "4xl": "24px",
    full: "9999px",
    lg: "10px",
    "3xl": "20px",
  },
  spacing: {
    none: "0px",
    xxs: "2px",
    xs: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    "2xl": "20px",
    "3xl": "24px",
    "4xl": "32px",
    "6xl": "48px",
    "7xl": "64px",
    "8xl": "80px",
    "9xl": "96px",
    "10xl": "128px",
    "11xl": "160px",
    sm: "6px",
    "5xl": "40px",
  },
  density: {
    sm: "24px",
    md: "28px",
    lg: "32px",
    xl: "44px",
    xs: "20px",
  },
  width: {
    xxs: "320px",
    sm: "480px",
    lg: "640px",
    xl: "768px",
    "2xl": "1024px",
    "3xl": "1280px",
    "4xl": "1440px",
    "5xl": "1600px",
    "6xl": "1920px",
    md: "560px",
    "paragraph-max": "720px",
    xs: "384px",
  },
  container: {
    "max-width-desktop": "1280px",
    "padding-desktop": "32px",
    "padding-mobile": "16px",
  },
  typography: {
    "Font family/font-family-display": "Work Sans",
    "Font family/font-family-body": "Work Sans",
    "Font weight/regular": "Regular",
    "Font weight/regular-italic": "Italic",
    "Font weight/medium": "Medium",
    "Font weight/medium-italic": "Medium italic",
    "Font weight/semibold": "Semibold",
    "Font weight/semibold-italic": "Semibold italic",
    "Font weight/bold": "Bold",
    "Font weight/bold-italic": "Bold italic",
    "Font size/text-xs": "10px",
    "Font size/text-sm": "11px",
    "Font size/text-md": "12px",
    "Font size/text-lg": "14px",
    "Font size/text-xl": "16px",
    "Font size/display-xs": "18px",
    "Font size/display-sm": "20px",
    "Font size/display-md": "24px",
    "Font size/display-lg": "30px",
    "Font size/display-xl": "34px",
    "Font size/display-2xl": "38px",
    "Line height/text-xs": "18px",
    "Line height/text-sm": "20px",
    "Line height/text-md": "24px",
    "Line height/text-lg": "28px",
    "Line height/text-xl": "30px",
    "Line height/display-xs": "32px",
    "Line height/display-sm": "38px",
    "Line height/display-md": "44px",
    "Line height/display-lg": "60px",
    "Line height/display-xl": "72px",
    "Line height/display-2xl": "90px",
    "Font size/text-xxs": "9px",
    "Line height/text-2xs": "16px",
    "Line height/text-3xs": "14px",
    "Line height/text-4xs": "12px",
  },
  textStyles: {
    "Display 2xl/Regular": {
      fontFamily: "Work Sans",
      fontSize: "38px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "-2%",
      lineHeight: "90px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display 2xl/Medium": {
      fontFamily: "Work Sans",
      fontSize: "38px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "-2%",
      lineHeight: "90px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display 2xl/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "38px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "-2%",
      lineHeight: "90px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display 2xl/Bold": {
      fontFamily: "Work Sans",
      fontSize: "38px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "-2%",
      lineHeight: "90px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xl/Regular": {
      fontFamily: "Work Sans",
      fontSize: "34px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "-2%",
      lineHeight: "72px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xl/Medium": {
      fontFamily: "Work Sans",
      fontSize: "34px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "-2%",
      lineHeight: "72px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xl/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "34px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "-2%",
      lineHeight: "72px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xl/Bold": {
      fontFamily: "Work Sans",
      fontSize: "34px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "-2%",
      lineHeight: "72px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display lg/Regular": {
      fontFamily: "Work Sans",
      fontSize: "30px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "-2%",
      lineHeight: "60px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display lg/Medium": {
      fontFamily: "Work Sans",
      fontSize: "30px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "-2%",
      lineHeight: "60px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display lg/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "30px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "-2%",
      lineHeight: "60px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display lg/Bold": {
      fontFamily: "Work Sans",
      fontSize: "30px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "-2%",
      lineHeight: "60px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display md/Regular": {
      fontFamily: "Work Sans",
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "-2%",
      lineHeight: "44px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display md/Medium": {
      fontFamily: "Work Sans",
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "-2%",
      lineHeight: "44px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display md/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "-2%",
      lineHeight: "44px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display md/Bold": {
      fontFamily: "Work Sans",
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "-2%",
      lineHeight: "44px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display sm/Regular": {
      fontFamily: "Work Sans",
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "38px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display sm/Medium": {
      fontFamily: "Work Sans",
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "38px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display sm/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "38px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display sm/Bold": {
      fontFamily: "Work Sans",
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "38px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xs/Regular": {
      fontFamily: "Work Sans",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "32px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xs/Medium": {
      fontFamily: "Work Sans",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "32px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xs/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "32px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Display xs/Bold": {
      fontFamily: "Work Sans",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "32px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Regular": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Medium": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Bold": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "italic",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xl/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "30px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text lg/Regular": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Medium": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Bold": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "italic",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text lg/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "28px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text md/Regular": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Medium": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Bold": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "italic",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text md/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "24px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text sm/Regular": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Medium": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Bold": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text sm/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "italic",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text sm/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "11px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "20px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Regular": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Medium": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Bold": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text xs/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "italic",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xs/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "10px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "14px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Regular": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Medium": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Semibold": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Bold": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Regular italic": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "italic",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Regular underlined": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "underline",
    },
    "Text xxs/Medium italic": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Semibold italic": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "italic",
      fontWeight: 600,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
    "Text xxs/Bold italic": {
      fontFamily: "Work Sans",
      fontSize: "9px",
      fontStyle: "italic",
      fontWeight: 700,
      letterSpacing: "0%",
      lineHeight: "12px",
      fontStretch: "normal",
      textDecoration: "none",
    },
  },
}
