#! /bin/bash

echo "Pricing"

. ../../../config

#startCommand="dnx -p Adaptive.ReactiveTrader.Server.Pricing run"
startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run p"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm pricing 2&> garbage

docker run -d --net=host                       \
     --name pricing                            \
     $serversContainer:$vMajor.$vMinor.$vBuild \
     bash -c "$startCommand && $waitCommand"   \
     > container_id 

rm garbage

echo "  started"
echo " "
