#! /bin/bash

if [[ $# != 1 ]];then
  echo "pricing-run require build number"
fi
build=$1


echo "Pricing"

. ../../../config

startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run p"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm pricing 2&> garbage

docker run -d --net=host                       \
     --name pricing                            \
     $serversContainer:$vMajor.$vMinor.$build \
     bash -c "$startCommand && $waitCommand"   \
     > container_id 

rm garbage

echo " "
