#! /bin/bash

# fail fast
set -euo pipefail

. ../config

echo "Start web"
sudo docker run -d --net=host $webContainer.$TRAVIS_BUILD_NUMBER

echo "Start Eventstore"
sudo docker run -d --net=host $populatedEventstoreContainer.$TRAVIS_BUILD_NUMBER

echo "Start Broker"
sudo docker run -d --net=host $brokerContainer.$TRAVIS_BUILD_NUMBER

echo "Start ReferenceDataRead"
sudo docker run -d --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.Launcher run ref && while true; do echo ping; sleep 60; done"

echo "Start Pricing"
sudo docker run -d --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.Launcher run p && while true; do echo ping; sleep 60; done"

echo "Start Trade Execution"
sudo docker run -d --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.Launcher run exec && while true; do echo ping; sleep 60; done"

echo "Start Blotter"
sudo docker run -d --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.Launcher run b && while true; do echo ping; sleep 60; done"

echo "Start Analytics"
sudo docker run -d --net=host $serversContainer.$TRAVIS_BUILD_NUMBER bash -c "dnx --configuration Release -p Adaptive.ReactiveTrader.Server.Launcher run a && while true; do echo ping; sleep 60; done"
