#! /bin/bash

build=""
if [[ $1 != "" && $1 != "release" ]];then
  build=".$1"
fi

# fail fast
set -euo pipefail

echo "Broker"

. ../../../config

docker rm broker 2&> garbage || true

docker run -d --net=host    \
     --name broker          \
     $brokerContainer$build \
     > container_id 

rm garbage

echo " "
