#! /bin/bash

echo "Broker"

docker rm broker 2&> garbage

docker run -d --net=host        \
     --name broker              \
     weareadaptive/at-broker    \
       bash -c "crossbar start" \
     > container_id 

rm garbage

echo "  started"
echo " "
