#! /bin/bash

build=""
if [[ $1 != "" ]];then
  build=".$1"
fi

echo "TradeExecution"

. ../../../config

startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run exec"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm tradeexecution 2&> garbage

docker run -d --net=host                     \
     --name tradeexecution                   \
     $serversContainer$build                 \
     bash -c "$startCommand && $waitCommand" \
     > container_id 

rm garbage

echo " "
