#! /bin/bash

if [[ $1 == "" ]];then
  echo "The build number is required for this step"
  exit 1
fi
build=$1

# fail fast
set -euo pipefail

echo ""
echo "==============================="
echo "Build ReactiveTrader containers"
echo ""

cd ../docker
./prepare build services $build
