#! /bin/bash

echo "Loading containers"

for container in "mono" "crossbar" "eventstore" "nginx" "dnupackage" "nodemodules"
do
  if [[ -e ~/docker/$container.tar ]]; then 
    docker load -i ~/docker/$container.tar && echo "$container loaded" 
  fi
done
