#! /bin/bash

if [[ $1 == "" ]];then
  echo "The build number is required for this step"
  exit 1
fi
build=$1

# fail fast
set -euo pipefail

docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
${root_directory}/deploy/docker/prepare push services $build
