#! /bin/bash

if [[ $1 == "" ]];then
  echo "The build number is required for this step"
  exit 1
fi
build=$1

# fail fast
set -euo pipefail

echo ""
echo "============================="
echo "Run ReactiveTrader containers"
echo ""

cd ../docker
./circleci.runAll $build release
cd ../e2e
