#! /bin/bash

. ../config

# Here ~ refer to the home in circleci

mkdir -p ~/docker

echo "Saving containers"
docker save $dotnetContainer     > ~/docker/dotnet.tar
docker save $crossbarContainer   > ~/docker/crossbar.tar
docker save $eventstoreContainer > ~/docker/eventstore.tar
docker save $nginxContainer      > ~/docker/nginx.tar
