#! /bin/bash

#fail fast
set -euo pipefail

echo ""
echo "=============================="
echo "Test ReactiveTrader containers"
echo ""

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
${root_directory}/deploy/docker/testAll
