#! /bin/bash

release_mode=""
if [[ $1 == "release" ]];then
  release_mode="--configuration Release"
  build=""
elif [[ $1 != "" ]];then
  build=".$1"
fi
if [[ $2 == "release" ]];then
  release_mode="--configuration Release"
fi

#fail fast
set euo -pipefail

container_name="blotter"
echo "${container_name}"

# load configuration
this_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_directory="${this_directory}/../../../.."
. ${root_directory}/deploy/config

# remove
if [[ "$(docker ps -q -a --filter name=${container_name})" != "" ]]
then docker rm ${container_name} > /dev/null
fi

# start
start_command="dotnet run ${release_mode} -p Adaptive.ReactiveTrader.Server.Launcher b"
wait_command="while true; do echo ping; sleep 60; done"
docker run -d --net=host \
     --name ${container_name} \
     $serversContainer$build \
     bash -c "${start_command} && ${wait_command}" \
     > ${this_directory}/container_id

echo " "
