#! /bin/bash

. ../../../config

populateCommand=`cat "../../../../src/server/Populate Event Store.bat"`
docker run -d --net=host                       \
     $serversContainer:$vMajor.$vMinor.$vBuild \
     $populateCommand 

echo "  populated"
