#! /bin/bash

build=""
if [[ $1 != "" ]];then
  build=".$1"
fi

echo "EventStore"

. ../../../config

docker rm eventstore 2&> garbage

docker run -d --net=host              \
  --name eventstore                   \
  $populatedEventstoreContainer$build \
  > container_id

rm garbage

echo " "
