#! /bin/bash

build=""
if [[ $1 != "" && $1 != "release" ]];then
  build=".$1"
fi

# fail fast
set -euo pipefail

echo "EventStore"

. ../../../config

docker rm eventstore 2&> garbage || true

docker run -d --net=host              \
  --name eventstore                   \
  $populatedEventstoreContainer$build \
  > container_id

rm garbage

echo " "
