#! /bin/bash

if [[ $# != 1 ]];then
  echo "Web-run require build number"
fi
build=$1

echo "Web"

. ../../../config

docker rm web 2&> garbage

command="cp /localhost/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
docker run -d --net=host                  \
     --name web                           \
     $webContainer:$vMajor.$vMinor.$build \
     bash -c "$command"                   \
     > container_id 

rm garbage

echo " "
