#! /bin/bash

build=""
if [[ $1 != "" && $1 != "release" ]];then
  build=".$1"
fi

#fail fast
set euo -pipefail

container_name="web"
echo "${container_name}"

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../../.."
. ${root_directory}/deploy/config

# remove
if [[ "$(docker ps -q -a --filter name=${container_name})" != "" ]]
then docker rm ${container_name} > /dev/null
fi

# start
command="cp /localhost/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
docker run -d --net=host \
     --name ${container_name} \
     $webContainer$build \
     bash -c "$command" \
     > container_id

echo " "
