apiVersion: v1
kind: Service
metadata:
  name: kube-ui-v3
  labels:
    k8s-app: kube-ui-v3
spec:
  selector:
    k8s-app: kube-ui-v3
  ports:
  - port: 7000
    targetPort: 8080
  type: "LoadBalancer"