export { default as Platform } from './platform'
export { PlatformAdapter, WindowConfig, openFinNotifications } from './adapters'
export { PlatformProvider } from './context'
export { withPlatform } from './withPlatform'
export { externalWindowDefault } from './externalWindowDefault'
