export { default as Platform } from './platform'
export { openFinNotifications, setupGlobalOpenfinNotifications } from './adapters'
export * from './adapters'
export { PlatformProvider } from './context'
export { withPlatform } from './withPlatform'
export { externalWindowDefault } from './externalWindowDefault'
