version: '3'
services:
  e2e:
    image: ${DOCKER_USER}/e2e:${BUILD_VERSION}
    build:
      dockerfile: Dockerfile
      context: ./e2e
    hostname: e2e
    container_name: e2e
    command: 'npm run e2e -- --chromeDriver=/usr/bin/chromedriver --baseUrl=http://nginx'
    depends_on:
      - client
      - nginx
      - nlp
      - servers
