#! /bin/bash

if [[ $1 == "" ]];then
  echo "usage:"
  echo "  $0 NAMESPACE"
  echo " "
  exit 1
fi
namespace=$1

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

${root_directory}/deploy/kubernetes/templates/generate_ns_manifest $namespace
kubectl="${root_directory}/deploy/clis/kubectl"
${kubectl} create -f deploy/kubernetes/manifests/ns.yml
