#! /bin/bash

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config
kubectl=${root_directory}/deploy/clis/kubectl
manifests_directory_in_container="deploy/kubernetes/manifests"
manifests_directory=${root_directory}/${manifests_directory_in_container}

name="minikubegate"
pod_manifest_name="${name}-pod.yml"

mkdir -p ${manifests_directory}

# namespace
${kubectl} create namespace ${name}

# pod
cat <<EOF > ${manifests_directory}/${pod_manifest_name}
apiVersion: v1
kind: Pod
metadata:
    name: ${name}
    namespace: ${name}
spec:
    containers:
        -   name: ${name}
            image: ${minikubegate_image}
            ports:
            -   containerPort: 80
                hostPort: 80
                name: "http"
            -   containerPort: 8000
                hostPort: 8000
                name: "broker"
            -   containerPort: 1113
                hostPort: 1113
                name: "eventstore-tcp"
            -   containerPort: 2113
                hostPort: 2113
                name: "eventstore"
EOF
${kubectl} create -f ${manifests_directory_in_container}/${pod_manifest_name}
