#! /bin/bash

usage() {
  echo " "
  echo " usage:"
  echo " "
  echo "    deploy NAMESPACE [BUILD_ID]"
  echo " "
  echo "- NAMESPACE is the environment that you define for kubernetes."
  echo "  It's a string like <test> or <production>"
  echo " "
  echo "- BUILD_ID is optional."
  echo "  It can be the build number or a string that you have defined at build time"
  echo " "
  echo " "
  echo "  ie: "
  echo "      $0 test"
  echo "      will start the environment test and deploy last version"
  echo " "
  echo "      $0 mypersonalenv 628"
  echo "      will start the environment mypersonalenv and deploy version 628"
  echo " "
  echo " Just ensure that your build is stored on dockerhub by looking at one of the image"
  echo "   https://hub.docker.com/u/adaptivetrader/dashboard/"
  echo " "
  exit 1
}

if [[ $# < 1 ]];then
  usage
fi
namespace=$1
build=$2

set -euo pipefail

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."

# generate manifest
# =================
templates_directory="${root_directory}/deploy/kubernetes/templates"

# namespace
${templates_directory}/generate_ns_manifest $namespace

# services
${templates_directory}/generate_svc_manifest web $namespace
${templates_directory}/generate_svc_manifest broker $namespace
${templates_directory}/generate_svc_manifest eventstore $namespace

# replication controller
${templates_directory}/generate_rc_manifest blotter           $namespace $build
${templates_directory}/generate_rc_manifest broker            $namespace $build
${templates_directory}/generate_rc_manifest eventstore        $namespace $build
${templates_directory}/generate_rc_manifest pricing           $namespace $build
${templates_directory}/generate_rc_manifest referencedataread $namespace $build
${templates_directory}/generate_rc_manifest tradeexecution    $namespace $build
${templates_directory}/generate_rc_manifest web               $namespace $build
${templates_directory}/generate_rc_manifest analytics         $namespace $build

# deploy on kubernetes
kubectl="${root_directory}/deploy/clis/kubectl"
manifests_directory_in_container="deploy/kubernetes/manifests"

# namespace
${kubectl} create -f ${manifests_directory_in_container}/ns.yml

  # service
${kubectl} create -f ${manifests_directory_in_container}/broker-svc.yml
${kubectl} create -f ${manifests_directory_in_container}/eventstore-svc.yml
${kubectl} create -f ${manifests_directory_in_container}/web-svc.yml

  # replication controller
${kubectl} create -f ${manifests_directory_in_container}/web-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/broker-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/eventstore-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/blotter-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/pricing-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/referencedataread-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/tradeexecution-rc.yml
${kubectl} create -f ${manifests_directory_in_container}/analytics-rc.yml

sleep 2

echo " "
echo " "
./kst $namespace
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
