#! /bin/bash

if [[ $# != 1 ]];then
  echo " "
  echo " usage:"
  echo "   $0 SECRET_NAME"
  echo " "
  echo " ie: $0 web-ssl"
  echo " "
  exit 1
fi
secretName=$1

set -euo pipefail

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"
manifest_directory_in_container="deploy/kubernetes/manifests"

${kubectl} create -f ${manifest_directory_in_container}/$secretName.yml
