#! /bin/bash
set -euo pipefail

echo "script outdated"
exit 1

namespace="nsgate"

# generate manifest
cd templates
cp nsgate/ns.yml ../manifests/ns.yml
./generate_svc_manifest nsgate $namespace
./generate_rc_manifest  nsgate $namespace ""
cd - > garbage && rm templates/garbage

# deploy on kubernetes
./kubectl create -f manifests/ns.yml
./kubectl create -f manifests/nsgate-svc.yml 
./kubectl create -f manifests/nsgate-rc.yml

echo " "
echo " "
./kst $namespace
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
