#! /bin/bash
set -euo pipefail

if [[ $1 == "" ]];then
  echo "usage:"
  echo "  $0 BUILD"
  echo " "
  exit 1
fi
build=$1
service="nsgate"
namespace="nsgate"

# generate manifest
cd templates
cp nsgate/ns.yml ../manifests/ns.yml
./generate_svc_manifest $service $namespace
./generate_rc_manifest $service $namespace $build
cd - > garbage && rm templates/garbage

# deploy on kubernetes
./kubectl create -f manifests/ns.yml
./kubectl create -f manifests/$service-svc.yml 
./kubectl create -f manifests/$service-rc.yml

echo " "
echo " "
./kst $namespace
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
