#! /bin/bash

if [[ $# != 1 ]];then
  echo " "
  echo " usage:"
  echo "   $0 SECRET_NAME"
  echo " "
  echo " ie: $0 web-ssl"
  echo " "
  exit 1
fi
secretName=$1

set -euo pipefail

./kubectl create -f ./manifests/$secretName.yml
