#! /bin/bash

usage() {
  echo " "
  echo " usage:"
  echo " "
  echo "    deploy NAMESPACE BUILD"
  echo " "
  echo "- NAMESPACE is the environment that you define for kubernetes."
  echo "  It's a string like <test> or <production>"
  echo " "
  echo "- BUILD can be the build number or a string that you have defined at build time"
  echo "    you can use <last> to start latest master success build"
  echo " "
  echo " "
  echo "  ie: deploy test 192"
  echo "  ie: deploy mypersonalenv personnalbuild"
  echo " "
  echo " Just ensure that your build is stored on dockerhub by looking at one of the image"
  echo "   https://hub.docker.com/u/adaptivetrader/dashboard/"
  echo " "
  exit 1
}

if [[ $# != 2 ]];then
  usage
fi
namespace=$1
build=$2

if [[ $build == "last" ]];then
  cd ../circleCi
  build=`./circleCiApi lastMasterSuccessBuild`
  cd ../kubernetes
fi


# generate manifest
cd templates
  # namespace
  ./generate_ns_manifest $namespace
  
  # services
  ./generate_svc_manifest web $namespace
  ./generate_svc_manifest broker $namespace
  ./generate_svc_manifest eventstore $namespace

  # replication controller
  ./generate_rc_manifest blotter           $namespace $build
  ./generate_rc_manifest broker            $namespace $build
  ./generate_rc_manifest eventstore        $namespace $build
  ./generate_rc_manifest pricing           $namespace $build
  ./generate_rc_manifest referencedataread $namespace $build
  ./generate_rc_manifest tradeexecution    $namespace $build
  ./generate_rc_manifest web               $namespace $build
  
cd - > garbage && rm templates/garbage

# deploy on kubernetes
  # namespace
  ./kubectl create -f manifests/ns.yml
  
  # service
  ./kubectl create -f manifests/broker-svc.yml
  ./kubectl create -f manifests/eventstore-svc.yml
  ./kubectl create -f manifests/web-svc.yml
  
  # replication controller
  ./kubectl create -f manifests/web-rc.yml
  ./kubectl create -f manifests/broker-rc.yml  
  ./kubectl create -f manifests/eventstore-rc.yml
  ./kubectl create -f manifests/blotter-rc.yml
  ./kubectl create -f manifests/pricing-rc.yml
  ./kubectl create -f manifests/referencedataread-rc.yml
  ./kubectl create -f manifests/tradeexecution-rc.yml
  

echo " "
echo " "
./kst $namespace
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
