#! /bin/bash

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"

if [[ -z $1 ]]
then  namespace="--namespace=default"
else  namespace="--namespace=$1"
fi

echo " "                                       && \
echo -e "\e[32mCURRENT CLUSTER\e[39m"          && \
${kubectl} config current-context              && \
echo " "                                       && \
echo -e "\e[32mNAMESPACE\e[39m"                && \
echo "$1"                                      && \
echo " "                                       && \
echo -e "\e[32mDEPLOYMENTS\e[39m"              && \
${kubectl} get deployment $namespace           && \
echo " "                                       && \
echo -e "\e[32mSERVICES\e[39m"                 && \
${kubectl} get services $namespace             && \
echo " "                                       && \
echo -e "\e[32mRC\e[39m"                       && \
${kubectl} get rc $namespace                   && \
echo " "                                       && \
echo -e "\e[32mPODS\e[39m"                     && \
${kubectl} get pods $namespace                 && \
echo " "                                       && \
echo -e "\e[32mENDPOINTS\e[39m"                && \
${kubectl} get endpoints $namespace            && \
echo " "                                       && \
echo -e "\e[32mINGRESS\e[39m"                  && \
${kubectl} get ingress $namespace              && \
echo " "                                       && \
echo -e "\e[32mNODES\e[39m"                    && \
${kubectl} get nodes $namespace                && \
echo " "
