#! /bin/bash

# kst as Kubernetes STatus

if [[ -z $1 ]]
then
        namespace="--namespace=default"
else
        namespace="--namespace=$1"
fi
echo -e "\e[92mSERVICES\e[39m"     && \
./kubectl get services $namespace  && \
echo " "                           && \
echo -e "\e[92mRC\e[39m"           && \
./kubectl get rc $namespace        && \
echo " "                           && \
echo -e "\e[92mPODS\e[39m"         && \
./kubectl get pods $namespace      && \
echo " "                           && \
echo -e "\e[92mENDPOINTS\e[39m"    && \
./kubectl get endpoints $namespace && \
echo " "                           && \
echo -e "\e[92mINGRESS\e[39m"      && \
./kubectl get ingress $namespace   && \
echo " "                           && \
echo -e "\e[92mNODES\e[39m"        && \
./kubectl get nodes $namespace     && \
echo " "
