#! /bin/bash

set -euo pipefail

if [[ ! -f ../config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config and fill informations"
    echo " "
    exit 1
fi
. ../config

cacheFolder=$(pwd)/../cache
currentFolder=$(pwd)

docker run --rm -ti                       \
  --net=host                              \
  -v /$cacheFolder/.config://root/.config \
  -v /$cacheFolder/.kube://root/.kube     \
  -v /$currentFolder:/currentFolder       \
  -w //currentFolder                      \
  $gcloudContainer:$vGcloud kubectl $@
