#! /bin/bash

if [[ $1 == "" ]];then
  echo "usage:"
  echo "  $0 BUILD"
  echo " "
  exit 1
fi
build=$1

set -euo pipefail

namespace="nsgate"
service="nsgate"
. ../config

# generate manifest
cd templates
manifestFolder="../manifests"
rcFile="$manifestFolder/$service-rc.yml"

mkdir -p $manifestFolder

cp ./$service/rc.yml $rcFile

sed -ie "s/__MAJOR__/$nsGateContainer_major/g" $rcFile
sed -ie "s/__MINOR__/$nsGateContainer_minor/g" $rcFile
sed -ie "s/__BUILD__/$build/g" $rcFile
sed -ie "s|__DOCKERIMAGE__|$nsGateContainer$build|g" $rcFile
sed -ie "s/__NAMESPACE__/$namespace/g" $rcFile
cd ..


# deploy on kubernetes
./kubectl stop -f manifests/nsgate-rc.yml
./kubectl create -f manifests/nsgate-rc.yml


# get the namespace informations
echo " "
echo " "
./kst $namespace
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
