#! /bin/bash

if [[ $1 == "" ]];then
  echo "usage:"
  echo "  $0 BUILD"
  echo " "
  exit 1
fi
build=$1

set -euo pipefail

namespace="nsgate"
service="nsgate"

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# generate manifest
manifest_directory="${root_directory}/deploy/kubernetes/manifests"
replication_controller_file="${manifest_directory}/${service}-rc.yml"

mkdir -p ${manifest_directory}

cp ./$service/rc.yml ${replication_controller_file}
sed -ie "s/__MAJOR__/$nsGateContainer_major/g" ${replication_controller_file}
sed -ie "s/__MINOR__/$nsGateContainer_minor/g" ${replication_controller_file}
sed -ie "s/__BUILD__/$build/g" ${replication_controller_file}
sed -ie "s|__DOCKERIMAGE__|$nsGateContainer.$build|g" ${replication_controller_file}
sed -ie "s/__NAMESPACE__/$namespace/g" ${replication_controller_file}


# deploy on kubernetes
kubectl="${root_directory}/deploy/clis/kubectl"
${kubectl} delete -f manifests/nsgate-rc.yml
${kubectl} create -f manifests/nsgate-rc.yml


# get the namespace informations
kst="${root_directory}/deploy/kubernetes/kst"
echo " "
echo " "
${kst} ${namespace}
echo " "
echo " "
echo " Wait a moment and run <kst $namespace> to see the PODS generated on your cluster"
