#! /bin/bash

if [[ $# != 3 ]];then 
  echo " "
  echo "  usage:"
  echo "  $0 NAMESPACE SERVICE NEW_BUILD_ID"
  echo " "  
  exit 1
fi
service=$1
namespace=$2
build=$3

# fail fast
set -euo pipefail

. ../config
. ./helpers/functions.sh

dockerImage=""
if [[ $service == "broker" ]];then 
  dockerImage="$brokerContainer$build";
fi
if [[ $service == "web" ]];then 
  dockerImage="$webContainer$build";
fi
if [[ $service == "eventstore" ]];then 
  dockerImage="$populatedEventstoreContainer$build";
fi

dotnetServices="analytics blotter pricing referencedataread tradeexecution"
if listcontains "$dotnetServices" $service; then 
  dockerImage="$serversContainer$build";
fi 

./kubectl rolling-update \
  --namespace=$namespace \
  --image=$dockerImage   \
  --update-period=1s     \
  $service
