#! /bin/bash

# fail fast
set -euo pipefail

. ../config

if [[  $# != 2 ]];then
  echo " "
  echo " usage:"
  echo "    ./rollingUpdate NAMESPACE NEW_BUILD"
  echo " "
  exit 1
fi
namespace=$1
build=$2

./rollingUpdate $namespace web               $build
./rollingUpdate $namespace broker            $build
./rollingUpdate $namespace eventstore        $build
./rollingUpdate $namespace blotter           $build
./rollingUpdate $namespace pricing           $build
./rollingUpdate $namespace referencedataread $build
./rollingUpdate $namespace tradeexecution    $build
./rollingUpdate $namespace analytics         $build
