#! /bin/bash

# control configuration
if [[ ! -f ../config ]];then
  echo " "
  echo "usage:"
  echo "  you need to copy config from sample.config"
  exit 1
fi
. ../config
if [[ $vMajor = "" ]];then
  echo "kube: major version required, fill in adaptivetrader/deploy/config"
  exit 1
fi
if [[ $vMinor = "" ]];then
  echo "kube: minor version required, fill in adaptivetrader/deploy/config"
  exit 1
fi

if [[  $# != 2 ]];then
  echo " "
  echo " usage:"
  echo "    ./rollingUpdate NAMESPACE NEW_BUILD"
  echo " "
  exit 1
fi
namespace=$1
build=$2

./rollingUpdate $namespace web               $build
./rollingUpdate $namespace broker            $build
./rollingUpdate $namespace eventstore        $build
./rollingUpdate $namespace blotter           $build
./rollingUpdate $namespace pricing           $build
./rollingUpdate $namespace referencedataread $build
./rollingUpdate $namespace tradeexecution    $build
