#! /bin/bash

# fail fast
set -euo pipefail

. ../config

if [[  $# != 2 ]];then
  echo " "
  echo " usage:"
  echo "    ./rollingUpdate NAMESPACE NEW_BUILD"
  echo " "
  exit 1
fi
namespace=$1
build=$2

for service in "web" "broker" "eventstore" "blotter" "pricing" "referencedataread" "tradeexecution" "analytics"; do
  echo " "
  echo "==========="
  echo $service
  echo "==========="
  ./rollingUpdate $namespace $service $build
done
