#! /bin/bash

if [[ $1 == "" ]];then
  echo -e "\e[32mUsage:\e[39m"
  echo "  $0 NAMESPACE"
  echo " "
  exit 1
fi
namespace=$1

set -euo pipefail

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
templates_directory_in_container="deploy/kubernetes/templates"
kubectl="${root_directory}/deploy/clis/kubectl"

${kubectl} delete -f ${templates_directory_in_container}/testtools/pod.yml --namespace=$namespace && echo "waiting for pod to be deleted" || true

needtowait=true
while $needtowait; do
  ${kubectl} create -f ${templates_directory_in_container}/testtools/pod.yml --namespace=$namespace && needtowait=false \
  || echo "waiting for pod to be deleted" && sleep 10
done

needtowait=true
while true; do
  ${kubectl} exec --namespace=$namespace -ti testtools bash && needtowait=false \
  || echo "waiting for pod to be started" && sleep 10
done
