#! /bin/bash

# control configuration
if [[ ! -f ../config ]];then
    echo " "
    echo "usage:"
    echo "  you need to copy config from sample.config"
    exit 1
fi
. ../config
if [[ $vMajor = "" ]];then
  echo "kube: major version required, fill in adaptivetrader/deploy/config"
  exit 1
fi
if [[ $vMinor = "" ]];then
  echo "kube: minor version required, fill in adaptivetrader/deploy/config"
  exit 1
fi

if [[  $# != 4 ]];then
  echo " "
  echo " usage:"
  echo "    ./resize NAMESPACE SERVICE BUILD NEW_COUNT"
  echo " "
  exit 1
fi
namespace=$1
service=$2
build=$3
count=$4


# create or clean folder
mkdir -p manifests

# generate manifests
cd templates
generate_rc_manifest $service $namespace $build
cd ..

./kubectl scale --namespace=$namespace --replicas=$count -f manifests/$service-rc.yml 
