#! /bin/bash

# fail fast
set -euo pipefail

. ../config

if [[ $# < 3 ]];then
  echo "parameter error: "
  echo "  usage:"
  echo "  $0 NAMESPACE SERVICE NEW_COUNT"
  exit 1
fi
namespace=$1
service=$2
count=$3

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
kubectl="${root_directory}/deploy/clis/kubectl"

${kubectl} scale --namespace=$namespace --replicas=$count rc $service
