#!/bin/bash
NAME=$1

if [[ $NAME == "" ]];then
  echo "Usage:"
  echo $0 "local|gcloud"
  exit 1
fi

if [[ ! -f ../config ]];then
  echo "Config file does not exist. See deploy/README.md"
  exit 1
fi

. ../config
if [[ $NAME == "gcloud" ]];then
  NAME=gke_$kube_project\_$kube_zone\_$kube_cluster
fi



EXISTS=`./kubectl config view | grep "name: $NAME" | wc -l`

if [[ $EXISTS == "0" && $NAME == "local" ]];then
  echo "local doesn't exist, creating config"
  ./kubectl config set-context local --server=127.0.0.1
  EXISTS=1
fi



if [[ $EXISTS -gt "0" ]];then
  echo "Found config"
  ./kubectl config use-context $NAME
else
  cd ../googleCloudEngine
  ./getCredentials
  cd ../kubernetes
  EXISTS=`./kubectl config view | grep "name: $NAME" | wc -l`
  if [[ $EXISTS > 0 ]];then
    ./kubectl config use-context $NAME
  else 
    echo "Can't find cluster name"
    exit 1
  fi
fi
