#! /bin/bash

# exit on first error
set -euo pipefail

# load configuration
root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
. ${root_directory}/deploy/config

# run gcloud container
docker run --rm -ti \
  -v rtc-gcloud-config:/root/.config \
  -v rtc-kubectl-config:/root/.kube \
  ${gcloudContainer} gcloud $@
