env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - prettier

overrides:
  [
    {
      files: ["*.{service-mock,mock,test,spec}.{ts,tsx}", "**/__mocks__/*"],
      rules:
        {
          "@typescript-eslint/no-explicit-any": 0,
          "@typescript-eslint/no-non-null-assertion": 0,
          "@typescript-eslint/no-unused-vars": 0,
          "@typescript-eslint/no-var-requires": 0,
        },
    },
  ]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "simple-import-sort"
rules:
  {
    "@typescript-eslint/no-loss-of-precision": 0,
    "simple-import-sort/imports": 2,
    "simple-import-sort/exports": 2,
  }

settings:
  react:
    version: detect
