#! /bin/bash

build=""
if [[ $1 != "" ]];then
  build=".$1"
fi

echo "Analytics"
. ../../../config

startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run a"
waitCommand="while true; do echo ping; sleep 60; done"

docker rm analytics 2&> garbage

docker run -d --net=host                     \
     --name analytics                        \
     $serversContainer$build                 \
     bash -c "$startCommand && $waitCommand" \
     > container_id 

rm garbage
echo " "
