export const OPENFIN_SNAPSHOT_CURRENT: string = 'OPENFIN_SNAPSHOT_CURRENT'
export const OPENFIN_SNAPSHOT_NAMES: string = 'OPENFIN_SNAPSHOT_NAMES'
export const OPENFIN_SNAPSHOTS: string = 'OPENFIN_SNAPSHOTS'
export const OPENFIN_SNAPSHOT_DEFAULT_NAME: string = 'RTC - Default'
