name: Branch

on:
  push:
    branches:
      - "**"

defaults:
  run:
    working-directory: packages/client

env:
  BUCKET_WEB: reactive-trader-web-builds
  BUCKET_OPENFIN: reactive-trader-openfin-builds
  BUCKET_FINSEMBLE: reactive-trader-finsemble-builds
  BUCKET_LAUNCHER: reactive-trader-launcher-builds

jobs:
  build:
    name: Build & deploy

    runs-on: ubuntu-20.04

    if: github.repository_owner == 'AdaptiveConsulting'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # URL_SUFFIX is used so we can append branch/<branch-name> to BASE_URL, or leave blank in the case of uat/dev where we do not need it
      - name: Set variables
        id: vars
        run: |
          echo "BRANCH=$(echo $GITHUB_REF_NAME  | sed 's/\//_/g')" >> $GITHUB_OUTPUT
          echo "ENVIRONMENT=$( ([[ $GITHUB_REF_NAME = env/uat ]] && echo 'uat') || ([[ $GITHUB_REF_NAME = master ]] && echo 'dev') || echo 'env' )" >> $GITHUB_OUTPUT
          echo "URL_SUFFIX=$( ([[ $GITHUB_REF_NAME = env/uat || $GITHUB_REF_NAME = master ]] && echo '') || echo /branch/$(echo $GITHUB_REF_NAME  | sed 's/\//_/g') )" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  openfin-end-to-end-test-fx:
    name: Openfin end-to-end test FX

    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: start openfin
        run: |
          npx of-automation https://openfin.env.reactivetrader.com/branch/RT5530_run_multiple_openfin_ci/config/rt-fx.json ./e2e/openfin.spec.js --chromeDriverOverride=112 --devToolsPort=9091 --closeRuntime=never
      - name: Run tests
        env:
          E2E_RTC_WEB_ROOT_URL: https://openfin.env.reactivetrader.com/branch/RT5530_run_multiple_openfin_ci
        run: |
          npm run e2e:openfin spot-tile.spec blotter.spec
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: packages/client/playwright-report/
          retention-days: 7
  

  openfin-end-to-end-test-credit:
    name: Openfin end-to-end test Credit

    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: start openfin
        run: |
          npx of-automation https://openfin.env.reactivetrader.com/branch/RT5530_run_multiple_openfin_ci/config/rt-credit.json ./e2e/openfin.spec.js --chromeDriverOverride=112 --devToolsPort=9091 --closeRuntime=never
      - name: Run tests
        env:
          E2E_RTC_WEB_ROOT_URL: https://openfin.env.reactivetrader.com/branch/RT5530_run_multiple_openfin_ci
        run: |
          npm run e2e:openfin credit.spec
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: packages/client/playwright-report/
          retention-days: 7