name: Deploy

on: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code: ${{ github.event.deployment.ref }}'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Set release tag
        run: echo "TAG=$(git describe)" >> $GITHUB_ENV

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_SERVICE_KEY }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials "${{ secrets.GOOGLE_CLUSTER }}" --zone "${{ secrets.GOOGLE_COMPUTE_ZONE }}"

      - name: Deploy
        env:
          DEPLOY_ENV: ${{ github.event.deployment.environment }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: ./deploy/deploy.sh

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          state: success
          deployment_id: ${{ github.event.deployment.id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          state: failure
          deployment_id: ${{ github.event.deployment.id }}
