name: Fork Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    working-directory: packages/client

jobs:
  build:
    name: Build

    runs-on: ubuntu-20.04

    if: ${{ github.event.pull_request.head.repo.fork }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Verify Quality (type checking, linting, format checking, tests)
        run: npm run verify

      - name: Build (web)
        run: |
          npm run build
          npm run storybook:build

      - name: Build (OpenFin)
        run: npm run openfin:build
