#! /bin/bash

echo "EventStore"

. ../../../../config

docker rm eventstore 2&> garbage

docker run -d --net=host   \
  --name eventstore        \
  weareadaptive/eventstore:$vEventstore \
  > container_id

rm garbage
echo "  started"

populateCommand=`cat "../../../../../src/server/Populate Event Store.bat"`
docker run --rm --net=host                          \
     adaptivetrader/servers:$vMajor.$vMinor.$vBuild \
     $populateCommand 

echo "  populated"
echo " "
