#! /bin/bash

if [[ $# < 2 ]];then 
  echo "parameter error: "
  echo "  usage:"
  echo "  $0 SERVICE NAMESPACE [BUILD_ID]"  
  exit 1
fi
service=$1
namespace=$2

. ../../config
. ../helpers/functions.sh

manifestFolder="../manifests"
svcFile="$manifestFolder/$service-svc.yml"

mkdir -p $manifestFolder

cp ./$service/svc.yml $svcFile

if [[ $service == "broker" ]];then 
  vMajor=$brokerContainer_major
  vMinor=$brokerContainer_minor 
fi
if [[ $service == "web" ]];then 
  vMajor=$webContainer_major
  vMinor=$webContainer_minor  
fi
if [[ $service == "eventstore" ]];then 
  vMajor=$populatedEventstoreContainer_major
  vMinor=$populatedEventstoreContainer_minor
fi

dotnetServices="analytics blotter pricing referencedataread tradeexecution"
if listcontains "$dotnetServices" $service; then 
  vMajor=$serversContainer_major
  vMinor=$serversContainer_minor
fi 

sed -i  "s/__SERVICE__/$service/g"     $svcFile
sed -i  "s/__MAJOR__/$vMajor/g"        $svcFile
sed -i  "s/__MINOR__/$vMinor/g"        $svcFile
sed -i  "s/__NAMESPACE__/$namespace/g" $svcFile
