#! /bin/bash

# usage
if [[ $# != 2 ]];then
  echo "generate_secret_manifest-usage:"
  echo "  $0 SECRET_NAME NAMESPACE"
  echo "  ie: $0 web-ssl demo"
  echo " "
  exit 1
fi
secret=$1
namespace=$2

set -euo pipefail

# prerequisite
crt="../certificates/server.crt"
key="../certificates/server.key"

if [[ ! -f $crt ]];then
  echo "no crt file found in deploy/kubernetes/certificate."
  echo "You can generate certificate by running ./generateNewCertificates in the deploy/kubernetes folder"
  exit 1
fi
if [[ ! -f $key ]];then
  echo "no key file found in deploy/kubernetes/certificate."
  echo "You can generate certificate by running ./generateNewCertificates in the deploy/kubernetes folder"
  exit 1
fi

. ../../config

base64=$(which base64)
if [[ $? != 0 ]];then
  echo "generate_secret_manifest: base64 executable needed"
  exit 1
fi

# generate base64 of the files
base64crt=$($base64 -i -w 0 $crt)
base64key=$($base64 -i -w 0 $key)

# generating the file
templateFile="./secret/$secret.yml"
resultingFile="../manifests/$secret.yml"
cp  $templateFile $resultingFile
sed -i "s|__NAMESPACE__|$namespace|g"   $resultingFile 
sed -i "s|__DOMAINNAME__|$domainName|g" $resultingFile
sed -i "s|__CRT__|$base64crt|g"         $resultingFile 
sed -i "s|__KEY__|$base64key|g"         $resultingFile 
