#! /bin/bash

if [[ $# != 1 ]];then
  echo "parameter error: namespace"
  exit 1
fi
namespace=$1

manifestFolder="../manifests"
nsFile="$manifestFolder/ns.yml"

mkdir -p $manifestFolder

cp ./ns.yml $nsFile

sed -ie "s/__NAMESPACE__/$namespace/g" $nsFile
