#! /bin/bash

if [[ $# != 1 ]];then
  echo "parameter error: namespace"
  exit 1
fi
namespace=$1

root_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../../.."

manifest_directory="${root_directory}/deploy/kubernetes/manifests"
mkdir -p ${manifest_directory}

namespace_manifest="${manifest_directory}/ns.yml"
cp "${root_directory}/deploy/kubernetes/templates/ns.yml" ${namespace_manifest}

sed -ie "s/__NAMESPACE__/${namespace}/g" ${namespace_manifest}
